// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySach.Models;

#nullable disable

namespace QuanLySach.Migrations
{
    [DbContext(typeof(QlsContext))]
    partial class QlsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySach.Models.LoaiSach", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("TenLoai")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSach", (string)null);
                });

            modelBuilder.Entity("QuanLySach.Models.NhaXuatBan", b =>
                {
                    b.Property<int>("MaXb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaXb"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tenxb")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaXb")
                        .HasName("PK__NhaXuatB__272520CA2C1F079C");

                    b.ToTable("NhaXuatBan", (string)null);
                });

            modelBuilder.Entity("QuanLySach.Models.Sach", b =>
                {
                    b.Property<int>("Masach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Masach"));

                    b.Property<int?>("Maloai")
                        .HasColumnType("int");

                    b.Property<int?>("Maxb")
                        .HasColumnType("int");

                    b.Property<string>("Tacgia")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tensach")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Masach")
                        .HasName("PK__Sach__9F923C88F7AD74A8");

                    b.HasIndex("Maloai");

                    b.HasIndex("Maxb");

                    b.ToTable("Sach", (string)null);
                });

            modelBuilder.Entity("QuanLySach.Models.Sach", b =>
                {
                    b.HasOne("QuanLySach.Models.LoaiSach", "LoaiSach")
                        .WithMany("Sach")
                        .HasForeignKey("Maloai");

                    b.HasOne("QuanLySach.Models.NhaXuatBan", "NXB")
                        .WithMany("Sach")
                        .HasForeignKey("Maxb");

                    b.Navigation("LoaiSach");

                    b.Navigation("NXB");
                });

            modelBuilder.Entity("QuanLySach.Models.LoaiSach", b =>
                {
                    b.Navigation("Sach");
                });

            modelBuilder.Entity("QuanLySach.Models.NhaXuatBan", b =>
                {
                    b.Navigation("Sach");
                });
#pragma warning restore 612, 618
        }
    }
}
